---
all:
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  hosts:
    work-laptop:
    pentest-laptop:
    home-desktop:
    work-desktop:

  children:
    workstations:
      hosts:
        work-laptop:
        pentest-laptop:
        home-desktop:
        work-desktop:
    work:
      hosts:
        work-laptop:
        pentest-laptop:
    wsl:
      hosts:
        work-laptop:
    arch:
      hosts:
        pentest-laptop:
        work-desktop:
    ubuntu:
      hosts:
        work-laptop:
    fedora:
      hosts:
        home-desktop:
