---
all:
  hosts:
    work-laptop:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
    pentest-laptop:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
    home-desktop:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

  children:
    workstations:
      hosts:
        work-laptop:
        pentest-laptop:
        home-desktop:
    work:
      hosts:
        work-laptop:
        pentest-laptop:
