---
# Install packages via pacman (bulk)

- name: Filter pacman packages (exclude skipped)
  ansible.builtin.set_fact:
    pacman_packages_filtered: >-
      {{ pacman_packages
         | rejectattr('skip_on', 'contains', 'pacman')
         | map(attribute='name')
         | list }}

- name: Install packages via pacman
  community.general.pacman:
    name: "{{ pacman_packages_filtered }}"
    state: present
  become: true
  when: pacman_packages_filtered | length > 0
