---
# Configuration: Chezmoi dotfiles and post-configuration

- name: Apply Dotfiles and Post-Configuration
  hosts: all
  gather_facts: true
  tags: [config]
  roles:
    - role: chezmoi
    - role: post_config
